import "./globals.css";
import { DM_Serif_Display, DM_Sans } from "next/font/google";

const dmSerif = DM_Serif_Display({
  weight: "400",
  subsets: ["latin"],
  display: "swap",
  variable: "--font-serif",
});

const dmSans = DM_Sans({
  weight: ["300", "400", "500", "600", "700"],
  subsets: ["latin"],
  display: "swap",
  variable: "--font-sans",
});

const SITE_URL = "https://pacomesaspool.com.ar";

export const metadata = {
  title: "Comprar Mesa de Pool Importada | Paco Mesas — Argentina",
  description:
    "¿Buscás una mesa de pool? Mesas de billar importadas de USA con pizarra de 3 piezas, madera maciza y paño profesional. Mejor calidad que las mesas nacionales, a precio accesible. Pedí el catálogo.",
  keywords: [
    "comprar mesa de pool",
    "mesa de pool",
    "mesa de pool argentina",
    "mejor mesa de pool",
    "mesa de billar precio",
    "mesa de pool profesional",
    "mesa de pool 8 pies",
    "mesa de billar argentina",
    "mesa de pool importada",
    "mesa de billar importada",
    "taco de pool profesional",
    "taco de pool importado",
    "mesa de pool mercado libre",
    "mesa de billar profesional",
    "mesa de pool usada importada",
    "mesa de pool pizarra 3 piezas",
    "comprar mesa de billar",
    "brunswick mesa de pool",
    "olhausen mesa de pool",
  ],
  metadataBase: new URL(SITE_URL),
  alternates: { canonical: "/" },
  openGraph: {
    title: "Paco Mesas — Mesas de Pool Importadas de USA | Argentina",
    description:
      "Mesas de billar americanas con pizarra de 3 piezas, madera maciza y paño profesional. Calidad superior al mercado argentino, precio accesible. Cupos limitados.",
    url: SITE_URL,
    siteName: "Paco Mesas",
    locale: "es_AR",
    type: "website",
    // OG image auto-generated by app/opengraph-image.jsx
  },
  twitter: {
    card: "summary_large_image",
    title: "Comprar Mesa de Pool Importada | Paco Mesas — Argentina",
    description:
      "Mesas de pool importadas de USA. Pizarra de 3 piezas, madera maciza, paño profesional. Mejor calidad, mejor precio que el mercado local.",
    // Twitter image auto-generated by app/opengraph-image.jsx
  },
  robots: { index: true, follow: true },
  other: {
    "geo.region": "AR",
    "geo.placename": "Argentina",
    "content-language": "es-AR",
  },
};

const faqJsonLd = {
  "@context": "https://schema.org",
  "@type": "FAQPage",
  mainEntity: [
    {
      "@type": "Question",
      name: "¿Las mesas de pool importadas son nuevas o usadas?",
      acceptedAnswer: {
        "@type": "Answer",
        text: "Son usadas en excelente estado. Cada unidad se inspecciona antes del embarque: se verifica que la pizarra no tenga fisuras, que la madera esté firme y que las gomas conserven su elasticidad. La calidad de juego es equivalente a una mesa nueva.",
      },
    },
    {
      "@type": "Question",
      name: "¿Qué marcas de mesas de pool importan a Argentina?",
      acceptedAnswer: {
        "@type": "Answer",
        text: "En mesas: Brunswick, Olhausen, Diamond y Valley. En tacos: Predator, Meucci, McDermott y Lucasi. La disponibilidad exacta varía según cada partida de importación.",
      },
    },
    {
      "@type": "Question",
      name: "¿Cuánto cuesta una mesa de pool importada en Argentina?",
      acceptedAnswer: {
        "@type": "Answer",
        text: "Una mesa importada de estas características tiene un precio comparable —y en muchos casos menor— al de las opciones que se comercializan como premium en el mercado argentino. La diferencia en calidad de materiales y construcción es muy significativa.",
      },
    },
    {
      "@type": "Question",
      name: "¿Cuánto tarda la entrega de una mesa de pool importada?",
      acceptedAnswer: {
        "@type": "Answer",
        text: "Desde la confirmación de la reserva, estimamos entre 60 y 90 días según la logística marítima y los tiempos de aduana.",
      },
    },
    {
      "@type": "Question",
      name: "¿Incluyen el armado de la mesa de pool?",
      acceptedAnswer: {
        "@type": "Answer",
        text: "El armado profesional se coordina por separado con técnicos especializados en tu zona. Una mesa con pizarra de tres piezas requiere instalación profesional para asegurar una nivelación correcta.",
      },
    },
    {
      "@type": "Question",
      name: "¿Dejar mis datos implica un compromiso de compra?",
      acceptedAnswer: {
        "@type": "Answer",
        text: "No. Te contactamos con el catálogo completo y los precios, y vos decidís si te interesa avanzar. Nos sirve para estimar la demanda real antes de confirmar la importación.",
      },
    },
    {
      "@type": "Question",
      name: "¿Qué diferencia tiene una mesa de pool con pizarra de 3 piezas?",
      acceptedAnswer: {
        "@type": "Answer",
        text: "La pizarra de tres piezas permite una nivelación mucho más precisa que la pizarra de una sola pieza. Cada sección se ajusta de forma independiente, lo que garantiza una superficie de juego perfectamente plana. Es el estándar en mesas de calidad profesional en todo el mundo.",
      },
    },
  ],
};

const orgJsonLd = {
  "@context": "https://schema.org",
  "@type": "Organization",
  name: "Paco Mesas",
  url: SITE_URL,
  description:
    "Importación directa de mesas de pool y tacos profesionales americanos a Argentina. Brunswick, Olhausen, Diamond, Predator. Calidad superior a mejor precio.",
  contactPoint: {
    "@type": "ContactPoint",
    telephone: "+54-9-11-3797-8242",
    contactType: "sales",
    areaServed: "AR",
    availableLanguage: "Spanish",
  },
};

const productJsonLd = {
  "@context": "https://schema.org",
  "@type": "Product",
  name: "Mesa de Pool Americana Importada",
  description:
    "Mesas de pool americanas importadas de USA. Marcas: Brunswick, Olhausen, Diamond. Pizarra de 3 piezas, madera maciza, gomas K66, paño profesional. Disponible en 8 y 9 pies.",
  brand: { "@type": "Brand", name: "Brunswick / Olhausen / Diamond" },
  offers: {
    "@type": "AggregateOffer",
    priceCurrency: "USD",
    availability: "https://schema.org/PreOrder",
    availableAtOrFrom: { "@type": "Place", name: "Argentina" },
  },
  category: "Mesas de Pool",
};

export default function RootLayout({ children }) {
  return (
    <html lang="es-AR" className={`${dmSerif.variable} ${dmSans.variable}`}>
      <head>
        <link rel="icon" href="/favicon.svg" type="image/svg+xml" />
        {/* Google Analytics — REEMPLAZAR G-XXXXXXXXXX con tu ID real de GA4
        <script async src="https://www.googletagmanager.com/gtag/js?id=G-XXXXXXXXXX" />
        <script dangerouslySetInnerHTML={{ __html: `
          window.dataLayer = window.dataLayer || [];
          function gtag(){dataLayer.push(arguments);}
          gtag('js', new Date());
          gtag('config', 'G-XXXXXXXXXX');
        `}} />
        */}
        <script
          type="application/ld+json"
          dangerouslySetInnerHTML={{ __html: JSON.stringify(faqJsonLd) }}
        />
        <script
          type="application/ld+json"
          dangerouslySetInnerHTML={{ __html: JSON.stringify(orgJsonLd) }}
        />
        <script
          type="application/ld+json"
          dangerouslySetInnerHTML={{ __html: JSON.stringify(productJsonLd) }}
        />
      </head>
      <body>{children}</body>
    </html>
  );
}
